version = 0.1
[default.deploy.parameters]
stack_name = "test1"
resolve_s3 = true
s3_prefix = "test1"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "UserPoolId=\"eu-west-1_dDfqIG226\" ClientName=\"test1\" UserPoolName=\"test1\""
