version = 0.1
[default.deploy.parameters]
stack_name = "samcrud"
resolve_s3 = true
s3_prefix = "samcrud"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Client=\"https://weather-api-sam-010.com\" ClientDomain=\"https://localhost\" TableName=\"WeatherDataTable\""
